create table schedule.t_task
(
    id        int generated by default as identity primary key,
    c_title   varchar(128) not null,
    c_date    date         not null,
    c_time    varchar      not null,
    c_details text check (length(c_details) > 1 and length(c_details) < 1000),
    unique (c_date, c_time)
);