create table schedule.t_task
(
    id        int generated by default as identity primary key,
    c_date    date         not null,
    c_time    varchar      not null,
    c_description text check (length(c_description) > 1 and length(c_description) < 1000),
    unique (c_date, c_time)
);

create table schedule.t_daily_task (
    id bigint primary key generated by default as identity,
    text varchar
);